apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
  finalizers:
    - kubernetes.io/pvc-protection
  name: prometheus-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound