---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-storage
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-storage