---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fuhsicloud
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage